version: "3"
services:
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  api:
    build:
      dockerfile: Dockerfile-dev
      context: ./api
    volumes:
      # don't try to overwrite app node modules
      - /app/node_modules
      # look at server directory, copy everything inside there
      # excluding node_modules
      # into app folder of container
      # this makes it so whenever we change something locally in our server
      # folder, that change is reflected in the container
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile-dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile-dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile-dev
      context: ./nginx
    ports:
      - "3050:80"
